version: '3'
services:

  db:
    image: mongo:4.2.8
    container_name: db
    ports:
      - "4000:27017"
    restart: always

  azure-storage:
    image: azure-storage
    build: 
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=videostreaming01;AccountKey=LqSG2uaswzoDp7xmnBU/M75+c1UUCXfGL4pzyR+HnWmDdRSuAeUekaxYYPgur9pRWoS/S4FLrXEw+AStgUISmQ==;EndpointSuffix=core.windows.net
    restart: "no"

  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: "no"